apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-word-count-ftp
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "gcr.io/spark-operator/spark-py:v3.0.0"
  imagePullPolicy: Always
  mainApplicationFile: ftp://kube-master.reksoft.ru/pub/word-count.py
  sparkVersion: "3.0.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 2
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 3
    onSubmissionFailureRetryInterval: 20
  sparkConf:
    "spark.hadoop.dfs.nameservices": "ns1,ns2"
    "spark.hadoop.dfs.ha.namenodes.ns1": "nn1,nn2"
    "spark.hadoop.dfs.ha.namenodes.ns2": "nn3,nn4"
    "spark.hadoop.dfs.namenode.rpc-address.ns1.nn1": "hadoop-nn1.reksoft.ru:8020"
    "spark.hadoop.dfs.namenode.rpc-address.ns1.nn2": "hadoop-nn2.reksoft.ru:8020"
    "spark.hadoop.dfs.namenode.rpc-address.ns2.nn3": "hadoop-nn3.reksoft.ru:8020"
    "spark.hadoop.dfs.namenode.rpc-address.ns2.nn4": "hadoop-nn4.reksoft.ru:8020"
    "spark.hadoop.dfs.client.failover.proxy.provider.ns1": "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider"
    "spark.hadoop.dfs.client.failover.proxy.provider.ns2": "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider"

  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "1024m"
    labels:
      version: 3.0.0
    serviceAccount: autodataspark-spark

  executor:
    cores: 1
    instances: 1
    memory: "1024m"
    labels:
      version: 3.0.0